# Generated by Django 5.0.3 on 2024-03-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
 
    ]
