# Generated by Django 5.0.3 on 2024-04-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extratime', '0001_initial'),
        ('parqueo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_date', models.DateField(default=None)),
                ('extra_time', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratime', to='extratime.extratime')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='parqueo.price')),
            ],
            options={
                'db_table': 'reservationdetails',
                'ordering': ['-created_at'],
            },
        ),
    ]
