# Generated by Django 5.0.3 on 2024-03-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0005_vehicleentry'),
        ('reserva', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('totalamount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extratime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reserva.extratime')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parqueo.price')),
            ],
            options={
                'db_table': 'details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
