# Generated by Django 5.0.3 on 2024-05-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0005_alter_details_extratime_alter_details_price'),
        ('reserva', '0002_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='vehicle_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_entry', to='parqueo.vehicleentry'),
        ),
    ]
