# Generated by Django 5.0.3 on 2024-03-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_details_delete_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
