# Generated by Django 5.0.3 on 2024-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reservation_vehicle_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No Presentado'), ('MODIFIED', 'Modificada')], default='PENDING', max_length=10),
        ),
    ]
