# Generated by Django 5.0.3 on 2024-04-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratime', '0001_initial'),
        ('parqueo', '0012_alter_details_extratime'),
        ('reserva', '0004_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='extratime.extratime')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='parqueo.price')),
            ],
            options={
                'db_table': 'reservationdetails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExtraTime',
        ),
    ]
