# Generated by Django 5.0.3 on 2024-04-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratime', '0001_initial'),
        ('reserva', '0006_reservation_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='extra_time',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='extratime.extratime'),
        ),
    ]
