# Generated by Django 5.0.3 on 2024-03-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_rol_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correo_auth',
            field=models.BooleanField(default=False),
        ),
    ]
