# Generated by Django 5.0.3 on 2024-05-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mobiletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletoken',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
