# Generated by Django 5.0.3 on 2024-05-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehicle_is_ownparking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='is_ownParking',
            new_name='is_ownparking',
        ),
    ]
