# Generated by Django 5.0.3 on 2024-03-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='address',
            field=models.TextField(),
        ),
    ]
