# Generated by Django 5.0.3 on 2024-05-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleentry',
            name='details',
        ),
        migrations.AddField(
            model_name='details',
            name='is_userexternal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='vehicle_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='parqueo.vehicleentry'),
        ),
        migrations.AddField(
            model_name='vehicleentry',
            name='is_userexternal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleentry',
            name='phone',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
