# Generated by Django 5.0.3 on 2024-05-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0002_remove_vehicleentry_details_details_is_userexternal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
