# Generated by Django 5.0.3 on 2024-03-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0003_openinghours'),
        ('vehiculos', '0003_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parqueo.parking')),
                ('type_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='vehiculos.typevehicle')),
            ],
            options={
                'db_table': 'price',
                'ordering': ['-created_at'],
            },
        ),
    ]
