# Generated by Django 5.0.3 on 2024-05-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0003_alter_details_endtime_alter_details_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='totalamount',
            field=models.FloatField(null=True),
        ),
    ]
