# Generated by Django 5.0.3 on 2024-05-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratime', '0001_initial'),
        ('parqueo', '0004_alter_details_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='extratime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_time', to='extratime.extratime'),
        ),
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parqueo.price'),
        ),
    ]
