# Generated by Django 5.0.3 on 2024-05-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0005_alter_details_extratime_alter_details_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='url_image',
            field=models.CharField(max_length=200),
        ),
    ]
