# Generated by Django 5.0.3 on 2024-04-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0006_remove_vehicleentry_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
