# Generated by Django 5.0.3 on 2024-04-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0006_remove_vehicleentry_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price_per_hour',
            new_name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='is_pricehour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='price',
            name='is_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PriceHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_hour', to='parqueo.price')),
            ],
            options={
                'db_table': 'pricehour',
                'ordering': ['-created_at'],
            },
        ),
    ]
