# Generated by Django 5.0.3 on 2024-04-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0007_alter_address_latitude_alter_address_longitude'),
        ('parqueo', '0007_rename_price_per_hour_price_price_price_is_pricehour_and_more'),
    ]

    operations = [
    ]
