# Generated by Django 5.0.3 on 2024-04-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0008_merge_20240419_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_entry_fee',
            field=models.BooleanField(default=True),
        ),
    ]
