# Generated by Django 5.0.3 on 2024-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0010_alter_pricehour_end_time_alter_pricehour_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehour',
            name='end_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pricehour',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
