# Generated by Django 5.0.3 on 2024-04-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratime', '0001_initial'),
        ('parqueo', '0011_alter_pricehour_end_time_alter_pricehour_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='extratime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='extratime.extratime'),
        ),
    ]
